logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: development

logging:
  level:
    root: DEBUG

---
logging:
  level:
    root: warn
spring:
  config:
    activate:
      on-profile: product
